# Generated by Django 5.2.9 on 2025-12-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComposioConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='User identifier used with Composio', max_length=255, unique=True)),
                ('connected_account_id', models.CharField(blank=True, help_text='Composio connected account ID', max_length=255)),
                ('trigger_id', models.CharField(blank=True, help_text='Composio trigger ID for email notifications', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Composio Connection',
                'verbose_name_plural': 'Composio Connections',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='Gmail message ID', max_length=255, unique=True)),
                ('thread_id', models.CharField(blank=True, db_index=True, help_text='Gmail thread ID', max_length=255)),
                ('subject', models.CharField(blank=True, max_length=1000)),
                ('sender', models.CharField(help_text='From address', max_length=500)),
                ('recipient', models.CharField(blank=True, help_text='To address', max_length=500)),
                ('body_text', models.TextField(blank=True, help_text='Plain text body')),
                ('body_html', models.TextField(blank=True, help_text='HTML body')),
                ('snippet', models.TextField(blank=True, help_text='Email preview snippet')),
                ('labels', models.JSONField(blank=True, default=list, help_text='Gmail labels')),
                ('received_at', models.DateTimeField(db_index=True, help_text='When email was received')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-received_at'],
            },
        ),
    ]
