# Generated by Django 5.2.9 on 2025-12-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composioconnection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-received_at']},
        ),
        migrations.RemoveField(
            model_name='composioconnection',
            name='connected_at',
        ),
        migrations.RemoveField(
            model_name='composioconnection',
            name='trigger_id',
        ),
        migrations.RemoveField(
            model_name='composioconnection',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='email',
            name='body_html',
        ),
        migrations.RemoveField(
            model_name='email',
            name='raw_payload',
        ),
        migrations.RemoveField(
            model_name='email',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='composioconnection',
            name='connected_account_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='composioconnection',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='body_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='email',
            name='message_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='received_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='recipient',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='email',
            name='snippet',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
