# Generated by Django 5.2.9 on 2025-12-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_composioconnection_options_alter_email_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composioconnection',
            options={'verbose_name': 'Composio Connection', 'verbose_name_plural': 'Composio Connections'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-received_at'], 'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
        migrations.AddField(
            model_name='composioconnection',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='composioconnection',
            name='trigger_id',
            field=models.CharField(blank=True, help_text='Composio trigger ID for email notifications', max_length=255),
        ),
        migrations.AddField(
            model_name='composioconnection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='composioconnection',
            name='webhook_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='composioconnection',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='Public webhook URL for receiving email notifications', max_length=500),
        ),
        migrations.AddField(
            model_name='email',
            name='body_html',
            field=models.TextField(blank=True, help_text='HTML body'),
        ),
        migrations.AddField(
            model_name='email',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='email',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='composioconnection',
            name='connected_account_id',
            field=models.CharField(blank=True, help_text='Composio connected account ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='composioconnection',
            name='user_id',
            field=models.CharField(help_text='User identifier used with Composio', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='body_text',
            field=models.TextField(blank=True, help_text='Plain text body'),
        ),
        migrations.AlterField(
            model_name='email',
            name='labels',
            field=models.JSONField(blank=True, default=list, help_text='Gmail labels'),
        ),
        migrations.AlterField(
            model_name='email',
            name='message_id',
            field=models.CharField(db_index=True, help_text='Gmail message ID', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='received_at',
            field=models.DateTimeField(db_index=True, help_text='When email was received'),
        ),
        migrations.AlterField(
            model_name='email',
            name='recipient',
            field=models.CharField(blank=True, help_text='To address', max_length=500),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(help_text='From address', max_length=500),
        ),
        migrations.AlterField(
            model_name='email',
            name='snippet',
            field=models.TextField(blank=True, help_text='Email preview snippet'),
        ),
        migrations.AlterField(
            model_name='email',
            name='thread_id',
            field=models.CharField(blank=True, db_index=True, help_text='Gmail thread ID', max_length=255),
        ),
    ]
