# Generated by Django 5.2.9 on 2025-12-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_composioconnection_options_alter_email_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composioconnection',
            name='webhook_enabled',
        ),
        migrations.RemoveField(
            model_name='composioconnection',
            name='webhook_url',
        ),
    ]
